### ISSUE TITLE
Broken hashira-web in typecheck phase caused by mergery didn't wait the CI result

### ISSUE THREAD

**Issue by kachick** [pankona/hashira#1162]
I don't know why some PRs merged and others are not

merged: https://github.com/pankona/hashira/pull/1154
blocked: https://github.com/pankona/hashira/pull/1161

@pankona Could you check?

**Comment by pankona** [comment]
Thank you for your reporting!

**Comment by pankona** [comment]
全然わからん

**Comment by pankona** [comment]
![Screenshot_20240217-112343](https://github.com/pankona/hashira/assets/6533008/129d2990-31e6-4256-8e8b-813561d95ce2)

一応プロテクションは入れているつもりではある

**Comment by kachick** [comment]
ここ自分もよくわかってはないんだけど、 choose をしてない状態じゃないですか。 で、こんときって全選択扱いみたいにはならなかった気がするんだよな・・・(mobu はそれで選んだはず)

**Comment by kachick** [comment]
https://dev.classmethod.jp/articles/github-branch-protection-make-status-checks-mandatory/

これとか

で、ここで required をつけると、今度はその required がそもそも走らないような時には automerge が効かなくなるので、全部のPRで重要な check を走らせる必要がある。それでいいなら良いんだけど、個人的にそれだと重たいCIとかを小さい変更に対しても必須で走らせる必要が出てくるから大きくて堅いプロジェクト以外では避けるようにはしてます・・・

**Comment by kachick** [comment]
尚 action が死にだしたのは https://github.com/pankona/hashira/actions/runs/6617058313/job/17972581260 で、4ヶ月前にstyled-components のメジャーバージョンアップがあったときからの様子

**Comment by kachick** [comment]
https://github.com/styled-components/styled-components/blob/22e8b7f233e12500a68be4268b1d79c5d7f2a661/.github/ISSU>
 https://github.com/styled-components/styled-components/issues/4062

styled-components が v6 から DefinitelyTyped 不要になったのにv5の type へ依存してる package.json なのでそのせいかと思ったんだけど、どっちかというとサードパーティの styled-normalize とやらが未だに v5 までしか対応してないのにstyled-components あげちゃってる ミスマッチしてるのが原因っぽい

https://github.com/sergeysova/styled-normalize/blob/1131a414d601d342e41c7558ed64d3bd9db1a854/README.md#L18

**Comment by kachick** [comment]
というのに加えて、 その後 vite 側でもエラーが増えた状態でマージされている。 v5 から v4 へ落とすと2つ解消する代わりに v4 へバックポートされていない https://github.com/vitejs/vite/issues/15714 で死ぬ。わりとずたぼろである。


vite の typecheck は良く壊れるので skipLibCheck 入れるか、v4の中でも更に古いバージョンまで落とすなりで解消と言うか見てみないふりは出来そう

**Comment by kachick** [comment]
"skipLibCheck": true, にすると ↑の styled-components  で起こってた問題ももみ消されてしまうので、やはり検知が更に遅れるだけという気はする・・・

**Comment by pankona** [comment]
ずたぼろはともかく、CI とおらないままマージしちゃうのが良くないですね。mergery で良いのかも含めてやり方を再確認したさありますな...。
調査ありがとうございます！

**Comment by kachick** [comment]
とりあえず https://github.com/pankona/hashira/pull/1163 へ現状解消PRを出しておきました！
