### ISSUE TITLE
delete a task on any panel

### ISSUE THREAD

**Issue by skanehira** [pankona/hashira#81]
I want to be able to delete a task on any panel.

example.

# add view.go
```:view.go
func (v *View) deleteTask(t *KeyedTask) error {
	t.IsDeleted = true
	return v.Delegate(UpdateTask, t)
}
```

# add keybinding.go
```:keybinding.go
func (v *View) ConfigureKeyBindings(g *gocui.Gui) error {
		ec.SetError(g.SetKeybinding(p.name, 'd', gocui.ModNone, v.KeyD()))
}

func (v *View) KeyD(*gocui.Gui, *gocui.View) error {
	return v.deleteTask(v.FocusedTask())
}

```

**Comment by pankona** [comment]
Thank you for suggestion and sample snippets.
These few days, I considered whether accept your suggestion or not.

Briefly, I'm sorry to say that I decided not to accept your suggestion at this moment.
Reasons as follows:
- One key deletion feature may cause unwanted task deletion by mis-operation.
- But currently hashira doesn't provide the way to undo the deletion.
- I believe current way for task deletion (first move to done, then delete a task by "x") helps not to occur such unwanted task deletion.

I think that if hashira supports undo for such unwanted operation, it is definitely good to introduce one key task deletion. Please let me defer to introduce the feature at that appropriate time.

Best regards. Thanks!
